name: mini-b2b-platform

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: ${port}
      NODE_ENV: ${NODE_ENV}
  postgres:
    image: postgres:16-alpine3.23
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/redis
    