name: mini-b2b-platform

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
  postgres:
    image: postgres:16-alpine3.23
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: b2b
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/redis
    